### ISSUE TITLE
Broken link for robot categories

### ISSUE THREAD

**Issue by robotpilot** [ros-infrastructure/robots.ros.org#132]
I report that the link below does not work properly.
http://robots.ros.org/categories

**Comment by sloretz** [comment]
The broken link is in the first paragraph of the main page (highlighted in green)

![broken_link](https://user-images.githubusercontent.com/4175662/38525730-3cfe9f42-3c08-11e8-83c3-a8e8aa98b591.png)

**Comment by robotpilot** [comment]
It is too old, so close it.
