### ISSUE TITLE
What do you think about adding sections on categories for Humanoids? Manipulator? Legged robot?

### ISSUE THREAD

**Issue by robotpilot** [ros-infrastructure/robots.ros.org#134]
Now, this site for ROS-enabled robots (http://robots.ros.org/) is divided into Aerial, Component, Ground, Marine, and Sensor. 

- Aerial (6) http://robots.ros.org/category/aerial/ 
- Component (20) http://robots.ros.org/category/component/
- Ground (91) http://robots.ros.org/category/ground/
- Marine (3) http://robots.ros.org/category/marine/
- Sensor (0) http://robots.ros.org/category/sensor/

I counted about 120 robots in total. But most of them are on the ground. Maybe this seems to be the obvious reason.
However, it is increasingly difficult for our community to find more and more robots, especially ground type robots. So I think we need to further subdivide the robots that belong to Ground.

What do you think about adding sections on categories for Humanoids? Manipulator? Legged robot?

**Comment by robotpilot** [comment]
I agree with you that it is difficult to classify all robots and I think tagging is a good idea.
However, I feel that there are too many robots belonging to the **Ground** category. This means that it is difficult for users to find robots in that category. I think it is acceptable level now, but if it increases to 200 .. 300, I think it is necessary to classify separately. :)

**Comment by IanTheEngineer** [comment]
I'd like to +1 the idea for having a robot arm category. I don't think having a section for arms or manipulators is going down the rabbit hole of "full taxonomy". There are many industrial robot arms in the world, provided by a plethora of manufacturers, but very few robot legs. @tfoote I'd like to propose collapsing the "sensor" and "component" categories into one, and shift the robot arms under their own category. The sensor category has 0 entries at this moment in time anyway: https://robots.ros.org/category/sensor/

I had a bit of free time this evening and doodled out an icon that I'd be happy to contribute to the new category. If this is acceptable to the maintainers and community, I'll submit a PR to add it.

![arm](https://user-images.githubusercontent.com/850874/43053021-60c973b0-8df8-11e8-924b-c5009ffc2101.png)

**Comment by tfoote** [comment]
Yeah, we do have a bunch of robot arms. That probably makes sense to add the Arm cagetory @IanTheEngineer 

I guess the sensors are "components" there's a lot of them listed here: http://wiki.ros.org/Sensors I guess a tag for each class of sensor would work pretty well too.

**Comment by robotpilot** [comment]
It is too old, so close it.
