### ISSUE TITLE
Ruby Version

### ISSUE THREAD

**Issue by swinterbotix** [ros-infrastructure/robots.ros.org#183]
Hi,

I'm trying to run the test_site.bash script but I'm getting the following error message during Step 6/13.

![image](https://user-images.githubusercontent.com/52669772/73024906-32b10d00-3df4-11ea-8278-9ae5e41a2d51.png)

Specifically:
ERROR: Error installing jekyll-sitemap:
               jekyll-sass-converter requires Ruby version >= 2.4.0.

It seems that it wants a Ruby version greater or equal to 2.4.0, but the one I currently have is ruby 2.3.1p112. Even after installing a Ruby version greater than 2.4.0, I still see this error. As an FYI, I am using Ubuntu Linux 16.04

**Comment by tfoote** [comment]
Please copy and past console output and not screenshot it. It makes it much harder to analyze and search for related content precisely.

The version of ruby that's important is the one inside the docker container, updating your system won't help.

**Comment by swinterbotix** [comment]
@tfoote,

Thanks! I tried running the bash script using your fix and it worked great! I appreciate your help.
