### ISSUE TITLE
Mousing over headings they fade to white and become invisible

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/robots.ros.org#21]
They shouldn't disappear.

**Comment by sloretz** [comment]
@tfoote Mind assigning this issue to me? I don't have access to this repo.

**Comment by tfoote** [comment]
@sloretz I've invited you to a team in this org so you can be assignable. Once you accept that I can assign you. 

For looking into this you'll want to tweak the styl files here: https://github.com/ros-infrastructure/robots.ros.org/tree/gh-pages/src/styl

**Comment by wjwwood** [comment]
I believe this is fixed in https://github.com/ros-infrastructure/robots.ros.org/pull/24.

**Comment by tfoote** [comment]
fixed in #24
