### ISSUE TITLE
Problem with run ./test_site.bash

### ISSUE THREAD

**Issue by Vegatic** [ros-infrastructure/robots.ros.org#272]
Hi, Im following the new steps for doing a local testing of the webpage of my robot.

I didnt have any problem in the previous steps using: 
1. python3 -m venv ~/ghrocker_venv

2.  ~/ghrocker_venv/bin/activate

3. pip install ghrocker

But Im having problem using Run ./test_site.bash
![Captura de pantalla de 2023-04-01 18-11-35](https://user-images.githubusercontent.com/129131284/229320176-fbae2460-3963-44de-8621-a2b7c6810340.png)

I have already install docker in my pc but maybe Am I using the run command wrong? Or maybe I have to put the folder in which the test_site.bash file is in another folder?

I would be grateful If you can help me with that :)

**Comment by tfoote** [comment]
Thanks, There's a more complete issue in #275 so I'm going to close this as duplicate.
