### ISSUE TITLE
Hamster robot

### ISSUE THREAD

**Issue by cogniteam** [ros-infrastructure/robots.ros.org#36]
Hi,
On the process of moving to the new format, someone renamed our robot Hampster.
Please rename back the page and the robot to Hamster. This is disturbing. 
Thanks.

**Comment by tfoote** [comment]
Sorry about that. I suspect that was my internal autocomplete when typing. I've fixed it. Feel free to open a PR to make any other changes to the content.

**Comment by cogniteam** [comment]
Hi,
No problem.
Thanks!
